name: Publish Helm charts
on:
  push:
    branches:
      - main
      - renovate/*
env:
  # renovate: datasource=github-releases depName=helm/helm
  HELM_VERSION: v3.18.5
  OCI_REPOSITORY_URL: oci://ghcr.io/freebitnami/charts
# Remove all permissions by default.
permissions: {}
jobs:
  build_charts:
    if: ${{ github.repository_owner == 'freebitnami' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out ref branch
        uses: actions/checkout@v5
        with:
          path: ref-branch
          submodules: 'true'
      - name: Check out gh-pages branch
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages
          persist-credentials: false
          fetch-depth: 0
      - name: Install helm
        run: |
          HELM_TARBALL="helm-${HELM_VERSION}-linux-amd64.tar.gz"
          curl -SsLfO "https://get.helm.sh/${HELM_TARBALL}" && sudo tar xf "$HELM_TARBALL" --strip-components 1 -C /usr/local/bin
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build new/updated charts
        run: |
          set -eu

          cd ref-branch/bitnami/bitnami

          find . -type f -exec sed -i "s#oci://registry-1.docker.io/bitnamicharts#${OCI_REPOSITORY_URL}#" {} \;
          find . -type f -name Chart.yaml -exec sed -i -E 's#https://github.com/bitnami/charts/tree/main/bitnami/.+#https://github.com/freebitnami/charts#' {} \;

          for chart_name in *; do
            if [[ ! -d "${chart_name}" ]]; then
              continue
            fi
            chart_dependencies=($(yq '[.dependencies[].name] | join(" ")' ${chart_name}/Chart.yaml))
            if (( ${#chart_dependencies[@]} )); then
              printf "${chart_name} %s\n" "${chart_dependencies[@]}" >> dependency-graph
            fi
          done
          
          for chart_name in $(tsort dependency-graph | tac); do
            if [[ ! -f ${chart_name}/Chart.yaml ]]; then
              continue
            fi

            cd ${chart_name}

            chart_version=$(yq .version Chart.yaml)

            if [[ "${GITHUB_REF_NAME}" == 'main' ]]; then
              # only process chart if not already present in the registry
              chart_artifact_metadata=$(docker buildx imagetools inspect ghcr.io/freebitnami/charts/${chart_name}:${chart_version} 2>&1 || :)

              # TODO improve detection of missing artifact: a different error message doesn't always mean that the chart is already in the registry
              if [[ "${chart_artifact_metadata}" == "ERROR: ghcr.io/freebitnami/charts/${chart_name}:${chart_version}: not found" ]]; then 
                echo "Building and pushing chart ${chart_name}:${chart_version} to OCI repository..."
                helm dependency update
                helm package --destination ../../../gh-pages .
                helm push ../../../gh-pages/${chart_name}-${chart_version}.tgz ${OCI_REPOSITORY_URL}
              else
                echo "Skip building chart ${chart_name}:${chart_version} as it's already in the registry"
                entry_in_chart_index=$(yq ".entries.${chart_name}[] | select(.version == \"${chart_version}\")" ../../../gh-pages/index.yaml)
                if [[ -z "${entry_in_chart_index}" ]]; then
                  helm pull --destination ../../../gh-pages ${OCI_REPOSITORY_URL}/${chart_name} --version ${chart_version}
                fi
              fi
            else
              # process chart unconditionally, but based on local charts and do not push to registry and do not update gh-pages branch
              echo "Building chart ${chart_name}:${chart_version}..."
              # modify "repository" property only when value is ${OCI_REPOSITORY_URL}, due to exception with kube-prometheus
              yq -i '.dependencies = (.dependencies.[] as $dependency ireduce ([]; . + $dependency + {"repository": $dependency.repository | sub("^oci://.+$", "file://../" + $dependency.name)}))' Chart.yaml
              helm dependency update
              helm package --destination ../../../gh-pages .
            fi

            cd ..
          done
      - name: Build chart index
        run: |
          cd gh-pages
          if ls *.tgz > /dev/null 2>&1; then
            cp index.yaml old-index.yaml
            helm repo index --url ${OCI_REPOSITORY_URL} --merge old-index.yaml .
            sed -E -i "s#(${OCI_REPOSITORY_URL}/.+)-(.+)\.tgz#\1:\2#" index.yaml
            rm old-index.yaml *.tgz
            # XXX maybe run `git diff` for logging purposes?
          fi
      - name: Commit and push updated chart index
        if: ${{ github.ref_name == 'main' }}
        uses: actions-js/push@master
        with:
          message: Update chart index
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ github.token }}
